"""add ai analysis fields

Revision ID: 8a5103463f7b
Revises: 0002_add_job_status_filter
Create Date: 2026-03-26 23:13:33.454489
"""

from alembic import op
import sqlalchemy as sa


revision = '8a5103463f7b'
down_revision = '0002_add_job_status_filter'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('ai_score', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('ai_analysis_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'ai_analysis_at')
    op.drop_column('jobs', 'ai_summary')
    op.drop_column('jobs', 'ai_score')
    # ### end Alembic commands ###
